// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SgIwLniIGHzFhCy0MWw53xX6GgPsKT4',
    appId: '1:667467650715:web:4217c713651196febcd83e',
    messagingSenderId: '667467650715',
    projectId: 'dronquick-84db1',
    authDomain: 'dronquick-84db1.firebaseapp.com',
    storageBucket: 'dronquick-84db1.appspot.com',
    measurementId: 'G-NQ3L6MND0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxe1Laj7O9FaWjQwBcH4XOKc5LMNd1SO8',
    appId: '1:667467650715:android:58ded974db6f4e7abcd83e',
    messagingSenderId: '667467650715',
    projectId: 'dronquick-84db1',
    storageBucket: 'dronquick-84db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEWL2YNgjjcEA1aJuwfY3WptotCb2pqM',
    appId: '1:667467650715:ios:7944c42a2c932653bcd83e',
    messagingSenderId: '667467650715',
    projectId: 'dronquick-84db1',
    storageBucket: 'dronquick-84db1.appspot.com',
    iosBundleId: 'com.example.dronapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZEWL2YNgjjcEA1aJuwfY3WptotCb2pqM',
    appId: '1:667467650715:ios:43378e59a99d2a02bcd83e',
    messagingSenderId: '667467650715',
    projectId: 'dronquick-84db1',
    storageBucket: 'dronquick-84db1.appspot.com',
    iosBundleId: 'com.example.dronapp.RunnerTests',
  );
}
